[project]
name = "ids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "python-nmap>=0.7.1",
    "scapy>=2.6.1",
    "scikit-learn>=1.7.1",
]
